.github/dependabot.yml
We do not release that often so daily updates makes no sense. Monthly will be enough
=> Reduce dependabot frequency from daily to monthly

.circleci/config.yml, .github/workflows/main.yml, README.md, stackrox-container-image-scanner/.mvn/wrapper/maven-wrapper.properties, stackrox-container-image-scanner/mvnw, stackrox-container-image-scanner/mvnw.cmd
To be independent from build environment let's use maven wrapper just
like we do with gradle. This will require only Java to be installed to
build the project.
https://maven.apache.org/wrapper/
=> Use maven wrapper

functionaltest-jenkins-plugin/src/test/groovy/ImageScanningTest.groovy
Jenkins LTS image was updated recently and it no longer violates policy.
This PR switch from LTS to 2.77 to ensure policy is violated.
=> Fix tests by using pinned jenkins image

.github/workflows/release.yml
Allow simple releases by using github actions.
=> Release from Github

stackrox-container-image-scanner/pom.xml
To release from github action we need to push commits and tags. The Github token is only supported in HTTPS connection (not SSH). This RP changes git connection strings from SSH to HTTPS to allow releases from github action.
=> Use git over https in pom.xml

.github/release-drafter.yml, .github/workflows/main.yml
Let's use releaser to automatically prepare release notes for us.
=> Configure releaser

stackrox-container-image-scanner/api.yaml, stackrox-container-image-scanner/src/test/java/com/stackrox/jenkins/plugins/services/ImageServiceTest.java, stackrox-container-image-scanner/src/test/resources/__files/v1/images/scan/minimal-with-names.json
This PR add `names` field introduced in `3.74`. This additional field causes errors because of issues in openapi-generator that does not handle unknown fields correctly when they are arrays.
Refs: 
- https://github.com/OpenAPITools/openapi-generator/issues/12550#issuecomment-1240358272
=> Update schema to include names in image added in 3.74

functionaltest-jenkins-plugin/src/test/groovy/ImageScanningTest.groovy, functionaltest-jenkins-plugin/src/test/groovy/ImageScanningTestNoFileTest.groovy
> The best defense against the Docker Hub rate limiting is to move any base images needed to quay.io directly. Quay.io does not restrict the number of public repositories for any user (either free or paid). In addition, quay.io does not restrict anonymous pulls against its repositories (either public or private) and only rate limits in the most severe circumstances to maintain service levels (e.g. tens of requests per second from the same IP address).
https://access.redhat.com/articles/5531191
=> Migrate from dockerhub to quay

.github/workflows/tests.yaml, functionaltest-jenkins-plugin/src/test/groovy/ImageScanningTest.groovy, functionaltest-jenkins-plugin/src/test/groovy/ImageScanningTestNoFileTest.groovy
Refs:
- https://github.com/stackrox/stackrox/pull/5348
=> Remove custom proxy

.github/dependabot.yml
If we enable auto merge then having a daily updates will not be a problem.
Since we now have e2e it's better to limit number of PRs in flight.
Refs:
- #238
=> Change dependabot to daily updates with limit

stackrox-container-image-scanner/src/main/java/com/stackrox/jenkins/plugins/StackroxBuilder.java, stackrox-container-image-scanner/src/main/resources/com/stackrox/jenkins/plugins/Messages.properties
When user wan to validate configuration currently they will get generic message and stack trace in details. 
This PR 
- alters the message based on root cause.
- fixes page crash (unhandled exception) when user input invalid URL 
- wrong answer from central (maybe it's not central at all or token is wrong)
- port is not listening
- wrong certificate
- unknown host
=> ROX-16728: On validation show concrete error

.github/workflows/tests.yaml
Per https://issues.redhat.com/browse/ROX-19985, and use the same key name as stackrox/stackrox. Cluster is created in the new project: https://github.com/stackrox/jenkins-plugin/actions/runs/6502381837/job/17661371924?pr=279#step:12:45 :heavy_check_mark:
=> ROX-19985: Test in RH GCP

stackrox-container-image-scanner/README.md
In the current implementation, running a scan on an Agent poses several challenges:
- **Backward Compatibility**: Enforcing Agent-based scans creates compatibility issues since Agents may not always be configured to connect to ACS (External Service).
- **Serialization**: We must ensure data is serialized to facilitate the transfer from an Agent to the Controller, allowing presentation of results to the user.
- **Testing Complexity**: Extending our end-to-end testing with an additional Controller/Agent setup is required to adequately test Agent functionality. However, this introduces complexity into our testing process.
In light of these challenges, it is more practical to run scans on the Controller rather than the Agent.
---
Refs: https://issues.jenkins.io/browse/JENKINS-71622
Closes: 
- …
=> Add information about running on controller

.github/workflows/tests.yaml
The `provision_gke_cluster()` signature changed with https://github.com/stackrox/stackrox/pull/8396
=> chore(CI): change call to gke.sh

.github/workflows/tests.yaml, functionaltest-jenkins-plugin/src/main/groovy/util/Config.groovy, functionaltest-jenkins-plugin/src/test/groovy/ImageScanningTest.groovy
Refactor the E2E tests to make use of the infractl clusters, removing the dependency on the stackrox repository.
This does create an overhead on the creation time of the cluster (it will now take 20-25 minutes to create the cluster) but that is acceptable for the lowered maintenance effort.
=> chore(e2e): refactor e2e tests

stackrox-container-image-scanner/src/main/java/com/stackrox/jenkins/plugins/services/ApiClientFactory.java, stackrox-container-image-scanner/src/test/java/com/stackrox/jenkins/plugins/services/ApiClientFactoryTest.java
This PR adds a  custom UserAgent for request made by plugin. The format is 
```xml
<plugin-name>/<plugin-version>:<jenkins-version> (<os>; <arch>) CI
```
Example:
```python
stackrox-container-image-scanner/1.4.1-SNAPSHOT_(private-a8df60e6-janisz):2.164.1 (Linux; amd64) CI
```
Refs:
https://github.com/stackrox/stackrox/blob/ff73e395a8b08bedd64ecf42d4cc0ccaa2de2673/pkg/clientconn/useragent.go#L28-L38
=> fix: set user agent

.github/dependabot.yml, stackrox-container-image-scanner/pom.xml
We previously hardcoded the paths to webjars, including their versions. When Dependabot updated dependencies, these hardcoded paths were not updated, leading to missing JS and CSS files.
To prevent this issue, this PR moves the versioning to a property, ensuring paths are dynamically updated. Since webjar changes affect the UI and we do not have visual regression tests in place, this PR also excludes webjars from Dependabot updates. Additionally, as there might be breaking changes in JS/CSS, this PR reverts the recent webjar upgrades.
- #338
- #340
- #369
- #416
=> fix: missing jquery

.github/workflows/main.yml
Current builds fails with `Error: Resource not accessible by integration` this should fix the problem by granting permissions
=> fix release draft

stackrox-container-image-scanner/src/main/java/com/stackrox/jenkins/plugins/services/ApiClientFactory.java
This PR increases HTTP timeout to 10 minutes to match roxctl defaults. In following PR we will make it configurable or add polling if api supports this feature.
- https://github.com/stackrox/stackrox/blame/4.8.1/roxctl/image/image.go#L24-L29
- https://github.com/stackrox/jenkins-plugin/issues/414
=> increase read timeout for HTTP

.github/workflows/tests.yaml
This in recent PR to speedup stackrox deployment I removed 2 minutes wait. The comment claims it's just for GKE but it looks like it's required to allow scanner setup. This PR adds 1 minute sleep. In the future after we update api.yml we can use scanner status health to detect when scanner is ready.
- https://github.com/stackrox/stackrox/pull/16314
=> fix: wait for scanner
